# Imports

In [238]:
import numpy as np
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

In [239]:
from pandas_profiling import ProfileReport

In [240]:
conn = sqlite3.connect("data\data_wildfire_usa.sqlite")

In [241]:
#fires = pd.read_sql_query("SELECT * FROM fires". conn)
# fires est un tableau comprenant des données sur les incendies de forêt pour la période 1992-2015 compilées à partir des systèmes de déclaration fédéraux, étatiques et locaux des États-Unis.

In [242]:
#fires.info()

In [243]:
#fires.head()

# Description des variables

1.   OBJECTID : ID : donnée a priori non nécessaire pour notre étude

2.   FOD_ID : Identificateur unique global qui ressemble à l'OBJECTID 

3.   FPA_ID : Identificateur unique nécessaires pour remonter jusqu'à l'enregistrement d'origine 

4.   SOURCE_SYSTEM_TYPE : Type de données source ou système d'où provient l'enregistrement (fédéral, non fédéral ou interagence) 

5.   SOURCE_SYSTEM : Nom ou autre identifiant de la données source ou système d'où provient l'enregistrement 

6.   NWCG_REPORTING_AGENCY : Active National Wildlife Coordinating Group = Groupe national de coordination de la faune. Identifiant d'unité pour l'agence qui prépare le rapport d'incendie.
  *   BIA = Bureau of Indian Affairs 
  *   BLM = Bureau of Land Management
  *   BOR = Bureau of Reclamation
  *   DOD = Department of Defense
  *   DOE = Department of Energy
  *   FS = Forest Service
  *   FWS = Fish and Wildlife Service
  *   IA = Interagency Organization
  *   NPS = National Park Service
  *   ST/C&L = State, County, or Local Organization
  *   TRIBE = Tribal Organization

7.   NWCG_REPORTING_UNIT_ID : Identifiant d'unité NWCG actif pour l'unité préparant le rapport d'incendie 

8.   NWCG_REPORTING_UNIT_NAME : Nom d'unité NWCG actif pour l'unité préparant le rapport d'incendie

9.   SOURCE_REPORTING_UNIT : Code de l'unité d'agence préparant le rapport d'incendie, basé sur le code/nom dans les données source 

10.  SOURCE_REPORTING_UNIT_NAME : Nom de l'unité de l'agence déclarante préparant le rapport d'incendie, basé sur le code/nom des données source 

11.  LOCAL_FIRE_REPORT_ID : Numéro ou code qui identifie de manière unique un rapport d'incident pour une unité de déclaration particulière et une année civile particulière 

12.  LOCAL_INCIDENT_ID : Numéro ou code qui identifie de manière unique un incident pour une organisation locale de gestion des incendies particulière au cours d'une année civile donnée 

13.  FIRE_CODE : code utilisé au sein de la communauté inter-agences des feux de forêt pour suivre et compiler les informations sur les coûts de la suppression des incendies d'urgence

14.  FIRE_NAME : Nom de l'incident, tiré du rapport d'incendie (primaire) ou du rapport ICS-209 (secondaire)

15.  ICS_209_INCIDENT_NUMBER : Identifiant d'incident (événement), issu du rapport ICS-209. 

16.  ICS_209_NAME : Nom de l'incident, tiré du rapport ICS-209. 

17.  MTBS_ID : Identifiant d'incident, à partir de l'ensemble de données de périmètre MTBS. 

18.  MTBS_FIRE_NAME : Nom de l'incident, issu de l'ensemble de données de périmètre MTBS. 

19.  COMPLEX_NAME : Nom du complexe sous lequel l'incendie a finalement été maîtrisé, lorsqu'il est discernable. 

20.  FIRE_YEAR : Année civile au cours de laquelle l'incendie a été découvert ou confirmé. 

21.  DISCOVERY_DATE : Date à laquelle l'incendie a été découvert ou confirmé. 

22.  DISCOVERY_DOY : Jour de l'année où l'incendie a été découvert ou confirmé. 

23.  DISCOVERY_TIME : Heure de la journée à laquelle l'incendie a été découvert ou confirmé. 
            
24.  STAT_CAUSE_CODE : Code de la cause (statistique) de l'incendie.

25.  STAT_CAUSE_DESCR : Description de la cause (statistique) de l'incendie. 

26.  CONT_DATE : Date à laquelle l'incendie a été déclaré maîtrisé ou autrement maîtrisé (mm/jj/aaaa où mm=mois, jj=jour et aaaa=année). 

27.  CONT_DOY : Jour de l'année où l'incendie a été déclaré maîtrisé ou autrement maîtrisé. 

28.  CONT_TIME : Heure de la journée à laquelle l'incendie a été déclaré maîtrisé ou maîtrisé (hhmm où hh=heure, mm=minutes). *

29.  FIRE_SIZE : Estimation des acres dans le périmètre final du feu. (1 acre anglo-saxon = 40,47 ares). **A FAIRE : voir s'il y a corrélation entre la taille du feu et le temps**

30.  FIRE_SIZE_CLASS : Code de la taille du feu basé sur le nombre d'acres dans les dépenses finales du périmètre d'incendie
  *   A = > 0 et <= 0,25 acre
  *   B = 0,26 à 9,9 acres
  *   C = 10,0 à 99,9 acres
  *   D = 100 à 299 acres
  *   E = 300 à 999 acres
  *   F = 1000 à 4999 acres
  *   G = 5000+ acres

31.  LATITUDE : Latitude (NAD83) pour l'emplacement ponctuel de l'incendie (degrés décimaux). 

32.  LONGITUDE : Longitude (NAD83) pour l'emplacement ponctuel de l'incendie (degrés décimaux). 

33.  OWNER_CODE : Code du propriétaire principal ou de l'entité responsable de la gestion du terrain au point d'origine de l'incendie au moment de l'incident.

34.  OWNER_DESCR : Nom du propriétaire principal ou de l'entité responsable de la gestion du terrain au point d'origine de l'incendie au moment de l'incident

35.  STATE : Code alphabétique à deux lettres de l'état dans lequel l'incendie a brûlé (ou s'est déclaré), basé sur la désignation nominale dans le rapport d'incendie. **Correspondance à faire avec la liste ci-dessous**

(AK=Alaska, AL=Alabama, AR=Arkansas, AZ=Arizona, CA=California, CO=Colorado, CT=Connecticut, DE=Delaware, DHS=Department of Homeland Security, DOC= Department of Commerce, DOD=Department of Defense, DOE=Department of Energy, DOI= Department of Interior, DOL=Department of Labor, FL=Florida, GA=Georgia, IA=Iowa, IA/GC=Non-Departmental Agencies, ID=Idaho, IL=Illinois, IN=Indiana, KS=Kansas, KY=Kentucky, LA=Louisiana, MA=Massachusetts, MD=Maryland, ME=Maine, MI=Michigan, MN=Minnesota, MO=Missouri, MS=Mississippi, MT=Montana, NC=North Carolina, NE=Nebraska, NG=Non-Government, NH=New Hampshire, NJ=New Jersey, NM=New Mexico, NV=Nevada, NY=New York, OH=Ohio, OK=Oklahoma, OR=Oregon, PA=Pennsylvania, PR=Puerto Rico, RI=Rhode Island, SC=South Carolina, SD=South Dakota, ST/L=State or Local Government, TN=Tennessee, Tribe=Tribe, TX=Texas, USDA=Department of Agriculture, UT=Utah, VA=Virginia, VI=U. S. Virgin Islands, VT=Vermont, WA=Washington, WI=Wisconsin, WV=West Virginia, WY=Wyoming).

36.  COUNTY : Comté, ou équivalent, dans lequel l'incendie s'est déclaré (ou a pris naissance), en fonction de la désignation nominale dans le rapport d'incendie.

37.  FIPS_CODE : Code à trois chiffres de la publication FIPS (Federal Information Process Standards) 6-4 pour la représentation des comtés et des entités équivalentes. **=> Donnée non nécessaire si on a le nom. Nécessaire seulement si cette donnée nous permet de combler des valeurs manquantes dans la colonne FIPS_NAME**

38.  FIPS_NAME : Nom du comté de la publication FIPS 6-4 pour la représentation des comtés et des entités équivalentes

39.  Shape : donnée inutile

# Statistiques

In [244]:
# Statistiques au format html
#prof = ProfileReport(fires)
#prof.to_file(output_file='rapport.html')

In [245]:
# Affichage des statistiques dans le notebook via la librairie pandas_profiling
#profile = ProfileReport(fires, title='Analyse du fichier WildFire', html={'style':{'full_width':True}})
#profile.to_notebook_iframe()

Suite à la méthode ProfileReport, nous pouvons déclarer :
- Sur 39 entrées : 14 sont des variables de tyme numérique, 24 de type catégorielle et 1 ne peut être exploitée
- Il y a 27% de valeurs manquantes dans le DataFrame
- Etant donné la part de valeurs manquantes dans les colonnes ICS_209_INCIDENT_NUMBER (98.6%), ICS_209_NAME (98.6%), MTBS_ID (99.4%), MTBS_FIRE_NAME (99.4%), COMPLEX_NAME (99.7%), ces colonnes ne seront pas utilisées pour l'étude.
- Il n'y a pas de doubons parfaits : les doublons seront à analyser en détail par colonne
- Certaines colonnes sont à haute cardinalité, c'est à dire qu'elles ont des contraintes (uniques) qui nous empêchent de les regrouper. 
- Les colonnes OBJECTID, FOD_ID et FPA_ID ont des valeurs uniques. FPA_ID a des valeurs disctintes à 99.9%, il faut analyser ce point.
- Pour certaines données, nous avons à la fois des codes et des libellés. Il faudra analyser s'il y a un lien entre ces données et si nous pouvons remplacer des valeurs manquantes.
- Certains formats de date ne sont pas lisibles

# Data Cleaning

In [246]:
# Le chargement du fichier initial est nécessaire dans cette cellule pour éviter tout message d'erreur ou mauvaise manipulation, si la cellule est ré-exécutée
fires = pd.read_sql_query("SELECT * FROM fires", conn)
# Suppression de la colonne Shape
fires = fires.drop(['Shape'], axis = 1)
# Renommage des colonnes : DAY à la place de DOY
fires = fires.rename(columns = {'DISCOVERY_DOY' : 'DISCOVERY_DAY', 'CONT_DOY' : 'CONT_DAY'})
fires.head()

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,...,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME
0,1,1,FS-1418826,FED,FS-FIRESTAT,FS,USCAPNF,Plumas National Forest,0511,Plumas National Forest,...,0.10,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas
1,2,2,FS-1418827,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,0.25,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer
2,3,3,FS-1418835,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,0.10,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado
3,4,4,FS-1418845,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,0.10,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine
4,5,5,FS-1418847,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,0.10,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine

## Examen du type/format de données

In [247]:
# Vérification de la colonne FIRE_YEAR
fires['FIRE_YEAR'].value_counts().sort_index()
# On a bien les années 1992 à 2015

1992     67975
1993     61989
1994     75955
1995     71472
1996     75574
1997     61450
1998     68370
1999     89363
2000     96416
2001     86587
2002     75656
2003     68261
2004     69279
2005     88604
2006    114004
2007     95573
2008     85378
2009     78325
2010     79889
2011     90552
2012     72769
2013     64780
2014     67753
2015     74491
Name: FIRE_YEAR, dtype: int64

In [248]:
# La colonne DISCOVERY_DATE n'est pas au bon format
# Changement du format de date de DISCOVERY_DATE
fires['DATE'] = pd.to_datetime(fires['DISCOVERY_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
# Vérification succinte du format
print('Vérification format DATE avec la colonne FIRE_YEAR : \n', pd.DataFrame(fires['DATE']).join(fires['FIRE_YEAR']))

Vérification format DATE avec la colonne FIRE_YEAR :
               DATE  FIRE_YEAR
0       2005-02-02       2005
1       2004-05-12       2004
2       2004-05-31       2004
3       2004-06-28       2004
4       2004-06-28       2004
...            ...        ...
1880460 2015-09-26       2015
1880461 2015-10-05       2015
1880462 2015-05-02       2015
1880463 2015-10-14       2015
1880464 2015-03-14       2015

[1880465 rows x 2 columns]

In [249]:
# La colonne CONT_DATE n'est pas au bon format et possède des valeurs manquantes
# Changement du format de date de CONT_DATE
fires['CONT_DATE_COR'] = pd.to_datetime(fires['CONT_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
# Vérification du format
fires['CONT_DATE_COR']

0         2005-02-02
1         2004-05-12
2         2004-05-31
3         2004-07-03
4         2004-07-03
             ...
1880460   2015-09-26
1880461          NaT
1880462          NaT
1880463          NaT
1880464          NaT
Name: CONT_DATE_COR, Length: 1880465, dtype: datetime64[ns]

D'après le résulat de ProfileReport, la variable FIRE_YEAR est fortement corrélée avec les variables DISCOVERY_DATE et CONT_DATE.
Si la variable CONT_DATE correspond à l'année de FIRE_YEAR, alors nous pouvons remplacer les 47.4% de valeurs manquantes de CONT_DATE par FIRE_YEAR

In [250]:
# On vérifie que CONT_DATE correspond à l'année de FIRE_YEAR
# Création d'une colonne et suppression des valeurs manquantes
fires['CONT_DATE_COR_INT'] = (fires['CONT_DATE_COR'].dt.year).fillna(0).astype(int)
# Différence entre CONT_DATE et FIRE_YEAR
fires['DIFF_YEAR'] = fires['CONT_DATE_COR_INT'] - fires['FIRE_YEAR']
# Vérification des différences entre les 2 colonnes
year = pd.DataFrame(fires['CONT_DATE_COR_INT']).join(fires['FIRE_YEAR']).join(fires['DIFF_YEAR'])
year.loc[(year['DIFF_YEAR']>0) & (year['DIFF_YEAR']<1992)].value_counts()

CONT_DATE_COR_INT  FIRE_YEAR  DIFF_YEAR
2011               2010       1            29
2013               2012       1            25
2015               2014       1            23
2006               2005       1            18
2008               2007       1            13
2009               2008       1            12
2003               2002       1            12
2005               2004       1             9
2002               2001       1             9
2004               2003       1             8
2000               1999       1             7
1995               1994       1             6
2007               2006       1             6
2012               2011       1             5
2009               2006       3             4
                   1999       10            4
2005               2003       2             4
1999               1998       1             4
1994               1993       1             4
2001               2000       1             3
1997               1996       1             3
2007               2002       5             2
2010               2009       1             2
2016               2015       1             2
2005               2002       3             2
1998               1997       1             2
1996               1995       1             2
2002               1995       7             2
2004               2001       3             1
2000               1996       4             1
1996               1994       2             1
2007               1997       10            1
1997               1992       5             1
1998               1995       3             1
2007               2000       7             1
2010               2001       9             1
1999               1994       5             1
2009               2007       2             1
                   2005       4             1
2007               2004       3             1
2009               2000       9             1
2005               2000       5             1
2009               1998       11            1
2002               1998       4             1
2008               2006       2             1
                   2004       4             1
2002               2000       2             1
2007               2005       2             1
1993               1992       1             1
dtype: int64

Au vu des écarts entre les dates, nous ne pouvons pas savoir s'il s'agit d'erreur ou bien s'il s'agit bien de l'année souhaitée.

## Etude des variables identiques ou similaires

Est ce que la variable OBJECTID = FOD_ID ?

In [251]:
(fires.OBJECTID == fires.FOD_ID).value_counts()

False    1880393
True          72
dtype: int64

Les 2 colonnes semblent être identiques mais l'ID de FOD_ID est décalé à partir de l'index 72. 
A priori ces données ne sont pas nécessaires pour l'étude. On ne s'en préoccupera pas.

Est ce qu'une valeur donnée dans la colonne SOURCE_SYSTEM correspond à une valeur spécifique de la colonne SOURCE_SYSTEM_TYPE ?

D'après le résultat de ProfileReport, la variable SOURCE_SYTEM_TYPE est fortement corrélée à la variable SOURCE_SYTEM. Cette dernière a 38 valeurs.

In [252]:
# Création DataFrame
source_sytem = pd.DataFrame(fires['SOURCE_SYSTEM_TYPE']).join(fires['SOURCE_SYSTEM'])
# On compte les doublons
print(source_sytem.duplicated().value_counts(), '\n')
print('On peut constater qu\'il y a 39 doublons donc que la variable SOURCE_SYTEM a 39 valeurs et non 38')
# On regroupe les données par SOURCE_SYSTEM et on compte les valeurs de l'autre variable.
group_by_source_syst = source_sytem.groupby(['SOURCE_SYSTEM'], as_index = False).value_counts()
print('Résultat :')
group_by_source_syst

True     1880426
False         39
dtype: int64

On peut constater qu'il y a 39 doublons donc que la variable SOURCE_SYTEM a 39 valeurs et non 38
Résultat :

   SOURCE_SYSTEM SOURCE_SYSTEM_TYPE   count
0       DOI-WFMI                FED  241423
1       FA-NFIRS             NONFED    3387
2    FS-FIRESTAT                FED  220356
3       FWS-FMIS                FED   19327
4       IA-AKACC          INTERAGCY    3713
5       IA-HIWMO          INTERAGCY    9714
6      IA-ICS209          INTERAGCY    1982
7      IA-ICS209             NONFED       1
8      IA-PRIITF          INTERAGCY   21802
9       ST-ALALS             NONFED   54951
10      ST-ARARS             NONFED   11303
11      ST-AZAZS             NONFED    3446
12      ST-CACDF             NONFED   87355
13      ST-COCOS             NONFED    2433
14      ST-CTCTS             NONFED    3379
15      ST-FLFLS             NONFED   45077
16      ST-GAGAS             NONFED   65061
17      ST-KYKYS             NONFED    6519
18      ST-LALAS             NONFED   16172
19      ST-MEMES             NONFED    7252
20      ST-MIMIS             NONFED    2139
21      ST-MOMOS             NONFED    9835
22      ST-MSMSS             NONFED   60513
23      ST-MTMTS             NONFED    2737
24       ST-NASF             NONFED  711236
25      ST-NCNCS             NONFED   65695
26      ST-NENES             NONFED      17
27      ST-NMNMS             NONFED    4433
28      ST-OKOKS             NONFED   15397
29      ST-ORORS             NONFED   18121
30      ST-SCSCS             NONFED   49281
31      ST-SDSDS             NONFED    3181
32      ST-TNTNS             NONFED   14777
33      ST-TXTXS             NONFED   57945
34      ST-UTUTS             NONFED    4470
35      ST-VAVAS             NONFED   10575
36      ST-WAWAS             NONFED    9648
37      ST-WIWIS             NONFED   14323
38      ST-WYWYS             NONFED    1489

Nous remarquons que la donnée IA-ICS209 est en double et nous pouvons émzettre l'hypothèse que certaines données soient mal orthographiées, telle que ST-WIWIS / ST-WYWYS.

Est ce qu'une valeur donnée dans la colonne NWCG_REPORTING_UNIT_ID correspond à une valeur spécifique de la colonne NWCG_REPORTING_UNIT_NAME ?

D'après le résultat de ProfileReport, la variable NWCG_REPORTING_UNIT_ID est fortement corrélée à la variable NWCG_REPORTING_UNIT_NAME. Elles ont respectivement 1640 et 1635 valeurs. On en conclue qu'une valeur ID ne correspond pas a une valeur NAME

In [310]:
# Création DataFrame
reporting = pd.DataFrame(fires['NWCG_REPORTING_UNIT_ID']).join(fires['NWCG_REPORTING_UNIT_NAME'])
# On regroupe les données par NWCG_REPORTING_UNIT_ID puis on compte les valeurs de l'autre variable.
group_by_reporting = reporting.groupby(['NWCG_REPORTING_UNIT_ID'], as_index = False).value_counts()

In [296]:
# On s'intéresse aux doublons de NWCG_REPORTING_UNIT_NAME
reporting_doublon = group_by_reporting[group_by_reporting['NWCG_REPORTING_UNIT_NAME'].duplicated(keep = False) == True].sort_values(by ='NWCG_REPORTING_UNIT_NAME')
reporting_doublon

     NWCG_REPORTING_UNIT_ID NWCG_REPORTING_UNIT_NAME  count
319                 USCOCUX            Custer County      8
1241                USSDCUX            Custer County      4
327                 USCODGX           Douglas County    226
1248                USSDDOX           Douglas County      8
392                 USCOJCX           Jackson County     22
1300                USSDJAX           Jackson County      1
406                 USCOLOX             Logan County      9
679                 USKSLGX             Logan County      1
313                 USCOCRD       Northwest District   5182
364                 USCOGJD       Northwest District   3781

Si NWCG_REPORTING_UNIT_NAME a des doublons il s'agit probablement d'une erreur dans le jeu de données ou d'un changement de code (dans le référentiel) en cours d'année.
Pour une question d'homogénéité, nous pouvons remplacer ces données par celles qui sont les plus utilisées.

In [288]:
# Remplacement des valeurs doublons
fires['NWCG_REPORTING_UNIT_ID'] = fires['NWCG_REPORTING_UNIT_ID'].replace(['USSDCUX', 'USSDDOX', 'USSDJAX', 'USKSLGX', 'USCOGJD'],['USCOCUX', 'USCODGX', 'USCOJCX', 'USCOLOX', 'USCOCRD'])

Est ce qu'une valeur donnée dans la colonne FIRE_CODE correspond à une valeur spécifique de la colonne FIRE_NAME ?

In [294]:
# Création DataFrame
fires_code_name = pd.DataFrame(fires['FIRE_CODE']).join(fires['FIRE_NAME'])
# On compte les doublons
print(fires_code_name.duplicated().value_counts(), '\n')
# On regroupe les données par FIRE_NAME et on compte les valeurs de l'autre variable.
group_by = fires_code_name.groupby(['FIRE_NAME'], as_index = False).value_counts()
group_by[group_by['count'] > 1].sort_values(by = 'FIRE_NAME')

True     1187560
False     692905
dtype: int64

       FIRE_NAME FIRE_CODE  count
858         0118      EK2A      2
1276        0183      EK2A      2
1535        0227      EK2A      2
1679        0250      EK2A      2
1685        0251      EK2A      2
...          ...       ...    ...
312284       ZOT      DZ9H      2
312282       ZOT      EK15      5
312285       ZOT      6300      2
312304      ZULU      EKT1      2
312314   ZUMWALT      EKW2      2

[7326 rows x 3 columns]

Il en résulte qu'un code ne correspond pas systématiquement à un seul nom de feu. Un même code peut posséder plusieurs noms et inversement.

Est ce qu'une valeur donnée dans la colonne SOURCE_REPORTING_UNIT correspond à une valeur spécifique de la colonne SOURCE_REPORTING_UNIT_NAME ?

In [309]:
# Création DataFrame
source_reporting = pd.DataFrame(fires['SOURCE_REPORTING_UNIT']).join(fires['SOURCE_REPORTING_UNIT_NAME'])
# On compte les doublons
print(source_reporting.duplicated().value_counts(), '\n')
# On regroupe les données
group_by_source_reporting = source_reporting.groupby(['SOURCE_REPORTING_UNIT'], as_index = False).value_counts().sort_values(by = 'SOURCE_REPORTING_UNIT')

True     1873584
False       6881
dtype: int64

In [326]:
# On s'intéresse aux doublons
source_reporting_doublon = group_by_source_reporting[group_by_source_reporting['SOURCE_REPORTING_UNIT_NAME'].duplicated() == True].sort_values(by ='SOURCE_REPORTING_UNIT_NAME')
source_reporting_doublon
# Pour les limiter, nous allons convertir les données majuscules en minuscules

KeyError: 'Plumas National Forest'

Pour cette variable également on s'aperçoit qu'un code ne correspond pas à un seul nom et inversement.

In [256]:
# Est ce qu'une valeur donnée dans la colonne STAT_CAUSE_CODE correspond à une valeur spécifique de la colonne STAT_CAUSE_DESCR ?
stat_cause = pd.DataFrame(fires['STAT_CAUSE_CODE']).join(fires['STAT_CAUSE_DESCR'])
print(stat_cause.duplicated().value_counts(), '\n')
group_by_stat = stat_cause.groupby(['STAT_CAUSE_CODE'], as_index = False).value_counts()
print('Résultat comparaison des 2 colonnes :')
group_by_stat
# La variable STAT_CAUSE_CODE correspond à une donnée de STAT_CAUSE_DESCR

True     1880452
False         13
dtype: int64

Résultat comparaison des 2 colonnes :

    STAT_CAUSE_CODE   STAT_CAUSE_DESCR   count
0               1.0          Lightning  278468
1               2.0      Equipment Use  147612
2               3.0            Smoking   52869
3               4.0           Campfire   76139
4               5.0     Debris Burning  429028
5               6.0           Railroad   33455
6               7.0              Arson  281455
7               8.0           Children   61167
8               9.0      Miscellaneous  323805
9              10.0          Fireworks   11500
10             11.0          Powerline   14448
11             12.0          Structure    3796
12             13.0  Missing/Undefined  166723

In [257]:
# Est ce qu'une valeur donnée dans la colonne OWNER_CODE correspond à une valeur spécifique de la colonne OWNER_DESCR ?
owner = pd.DataFrame(fires['OWNER_CODE']).join(fires['OWNER_DESCR'])
print(owner.duplicated().value_counts(), '\n')
group_by_owner = owner.groupby(['OWNER_CODE'], as_index = False).value_counts()
print('Résultat comparaison des 2 colonnes :')
group_by_owner
# La variable OWNER_CODE correspond à une donnée de OWNER_DESCR

True     1880449
False         16
dtype: int64

Résultat comparaison des 2 colonnes :

    OWNER_CODE            OWNER_DESCR    count
0          0.0                FOREIGN       15
1          1.0                    BLM    63278
2          2.0                    BIA   106819
3          3.0                    NPS    17524
4          4.0                    FWS    12191
5          5.0                   USFS   188338
6          6.0          OTHER FEDERAL     6452
7          7.0                  STATE    30790
8          8.0                PRIVATE   314822
9          9.0                 TRIBAL     8952
10        10.0                    BOR      285
11        11.0                 COUNTY     1841
12        12.0        MUNICIPAL/LOCAL     4236
13        13.0       STATE OR PRIVATE    71881
14        14.0  MISSING/NOT SPECIFIED  1050835
15        15.0      UNDEFINED FEDERAL     2206

In [258]:
# Est ce qu'une valeur donnée dans la colonne FIPS_CODE correspond à une valeur spécifique de la colonne FIPS_NAME ?
fips = pd.DataFrame(fires['FIPS_CODE']).join(fires['FIPS_NAME'])
print(fips.duplicated().value_counts(), '\n')
group_by_fips = fips.groupby(['FIPS_CODE'], as_index = False).value_counts()
print('Résultat comparaison des 2 colonnes :')
group_by_fips
# Pour cette variable également on s'aperçoit qu'un code ne correspond pas à un seul nom et inversement.

True     1877769
False       2696
dtype: int64

Résultat comparaison des 2 colonnes :

     FIPS_CODE            FIPS_NAME  count
0          001             Atlantic   3237
1          001                Adair   2828
2          001               Albany   2395
3          001                Adams   2140
4          001             Anderson   2080
...        ...                  ...    ...
2690       730      Petersburg City      2
2691       760      Richmond (city)      1
2692       800         Suffolk City     49
2693       810  Virginia Beach City     17
2694       810  Virginia Beach city      2

[2695 rows x 3 columns]

In [259]:
# Est ce que la variable FIRE_SIZE_CLASS correspond à la variable FIRE_SIZE ?
# Création d'une colonne
fires['FIRE_SIZE_CLASS_TEST'] = 0
# Création d'une liste de condition
conditionlist = [
    (fires['FIRE_SIZE'] <= 0.25),
    (fires['FIRE_SIZE'] >0.25) & (fires['FIRE_SIZE']<10),
    (fires['FIRE_SIZE'] >=10) & (fires['FIRE_SIZE'] <100),
    (fires['FIRE_SIZE'] >=100) & (fires['FIRE_SIZE'] <300),
    (fires['FIRE_SIZE'] >=300) & (fires['FIRE_SIZE'] <1000),
    (fires['FIRE_SIZE'] >=1000) & (fires['FIRE_SIZE'] <5000),
    (fires['FIRE_SIZE']>=5000)]

# Création d'une liste de choix
choicelist = ['A', 'B', 'C', 'D', 'E', 'F', 'G']

# Comparaison avec la colonne existante
fires['FIRE_SIZE_CLASS_TEST'] = np.select(conditionlist, choicelist)
(fires['FIRE_SIZE_CLASS_TEST'] == fires['FIRE_SIZE_CLASS']).value_counts()

True    1880465
dtype: int64

La colonne FIRE_SIZE_CLASS est conforme à la colonne FIRE_SIZE

## Examen des doublons

L'examen des doublons sur l'ensemble des colonnes du DataFrame peut se faire directement avec les résulats de ProfileReport. Cependant, pour plus de clareté nous allons détailler certains points

In [260]:
# Création d'un dictionnaire regroupant les colonnes et le nombre de doublons par colonne
doublons = {}
for col in fires.columns :
    duplicates = fires[col].duplicated().sum()
    doublons[col] = duplicates

doublons

{'OBJECTID': 0,
 'FOD_ID': 0,
 'FPA_ID': 3,
 'SOURCE_SYSTEM_TYPE': 1880462,
 'SOURCE_SYSTEM': 1880427,
 'NWCG_REPORTING_AGENCY': 1880454,
 'NWCG_REPORTING_UNIT_ID': 1878825,
 'NWCG_REPORTING_UNIT_NAME': 1878830,
 'SOURCE_REPORTING_UNIT': 1875473,
 'SOURCE_REPORTING_UNIT_NAME': 1876024,
 'LOCAL_FIRE_REPORT_ID': 1866956,
 'LOCAL_INCIDENT_ID': 1314550,
 'FIRE_CODE': 1708018,
 'FIRE_NAME': 1386831,
 'ICS_209_INCIDENT_NUMBER': 1857727,
 'ICS_209_NAME': 1860891,
 'MTBS_ID': 1869983,
 'MTBS_FIRE_NAME': 1872331,
 'COMPLEX_NAME': 1879048,
 'FIRE_YEAR': 1880441,
 'DISCOVERY_DATE': 1871699,
 'DISCOVERY_DAY': 1880099,
 'DISCOVERY_TIME': 1879024,
 'STAT_CAUSE_CODE': 1880452,
 'STAT_CAUSE_DESCR': 1880452,
 'CONT_DATE': 1871704,
 'CONT_DAY': 1880098,
 'CONT_TIME': 1879023,
 'FIRE_SIZE': 1866828,
 'FIRE_SIZE_CLASS': 1880458,
 'LATITUDE': 986404,
 'LONGITUDE': 882929,
 'OWNER_CODE': 1880449,
 'OWNER_DESCR': 1880449,
 'STATE': 1880413,
 'COUNTY': 1877009,
 'FIPS_CODE': 1880179,
 'FIPS_NAME': 1878766,
 'DATE': 1871699,
 'CONT_DATE_COR': 1871704,
 'CONT_DATE_COR_INT': 1880439,
 'DIFF_YEAR': 1880431,
 'FIRE_SIZE_CLASS_TEST': 1880458}

Le résultat de ce dictionnaire nous indique plusieurs choses :
1. Pour la plupart des variables, il n'existe que très peu de données distinctes car il y a beaucoup de doublons.
2. Pour les variables uniques :
    - telles que OBJECTID et FOD_ID, il n'existe pas de doublons. Il n'y a donc pas d'erreur dans ces données car elles sont uniques (en lien avec les résultats de la méthode ProfileReport).
    - En revanche, pour la variable FPA_ID, nous remarquons qu'il y a 3 doublons. Ces erreurs doivent être corrigées car FPA_ID est une donnée censée être unique

In [261]:
# Identification et correction des doublons de FPA_ID
fpa_doublon = fires[fires['FPA_ID'].duplicated(keep = False) == True]
fpa_doublon
# Les 3 doublons concernent les FPA_ID suivants : FS-1452833 ; ICS209_2009_KS-DDQ-128 et SFO-2015CACDFLNU003791

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,...,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,DATE,CONT_DATE_COR,CONT_DATE_COR_INT,DIFF_YEAR,FIRE_SIZE_CLASS_TEST
21986,21987,22093,FS-1452833,FED,FS-FIRESTAT,FS,USNMCIF,Cibola National Forest,0303,Cibola National Forest,...,USFS,NM,31,031,McKinley,2007-07-18,2007-07-26,2007,0,B
1065673,1065674,1300088,ICS209_2009_KS-DDQ-128,INTERAGCY,IA-ICS209,DOD,USKSFRQ,Fort Riley Kansas,KSDDQ,Fort Riley,...,OTHER FEDERAL,KS,Riley,161,Riley,2009-02-19,2009-02-19,2009,0,F
1565829,1565830,201432072,FS-1452833,FED,FS-FIRESTAT,FS,USNMCIF,Cibola National Forest,0303,Cibola National Forest,...,USFS,NM,031,031,McKinley,2012-07-03,2012-07-04,2012,0,A
1634979,1634980,201750002,ICS209_2009_KS-DDQ-128,INTERAGCY,IA-ICS209,DOD,USKSFRQ,Fort Riley Kansas,KSDDQ,Fort Riley,...,OTHER FEDERAL,KS,Riley,161,Riley,2012-03-04,2012-04-03,2012,0,F
1825692,1825693,300245030,SFO-2015CACDFLNU003791,NONFED,ST-NASF,ST/C&L,USCALNU,Sonoma-Lake Napa Unit,CALNU,Sonoma-Lake Napa Unit,...,UNDEFINED FEDERAL,CA,SONOMA,097,Sonoma,2015-05-12,2015-05-12,2015,0,B
1870332,1870333,300306586,SFO-2015CACDFLNU003791,NONFED,ST-NASF,ST/C&L,USCALNU,Sonoma-Lake Napa Unit,CALNU,Sonoma-Lake Napa Unit,...,MISSING/NOT SPECIFIED,CA,SOLANO,095,Solano,2015-07-01,NaT,0,-2015,A

In [262]:
# Examen des doublons
fpa_doublon.sort_values(by = 'FPA_ID', inplace = True)
for col in fpa_doublon.columns :
    if any(fpa_doublon.groupby(['FPA_ID'])[col].nunique()>1)  :
        print(fpa_doublon[['FPA_ID', col]])
        print('='*50)
# Au vu du nombre de donnée en doublon, nous pouvons supprimer les données qu'on ne peut pas expliquer ou bien les laisser.
# 3 doublons sur 1800000 observation ont peu d'impact.

                         FPA_ID  OBJECTID
21986                FS-1452833     21987
1565829              FS-1452833   1565830
1065673  ICS209_2009_KS-DDQ-128   1065674
1634979  ICS209_2009_KS-DDQ-128   1634980
1825692  SFO-2015CACDFLNU003791   1825693
1870332  SFO-2015CACDFLNU003791   1870333
==================================================
                         FPA_ID     FOD_ID
21986                FS-1452833      22093
1565829              FS-1452833  201432072
1065673  ICS209_2009_KS-DDQ-128    1300088
1634979  ICS209_2009_KS-DDQ-128  201750002
1825692  SFO-2015CACDFLNU003791  300245030
1870332  SFO-2015CACDFLNU003791  300306586
==================================================
                         FPA_ID LOCAL_FIRE_REPORT_ID
21986                FS-1452833                   46
1565829              FS-1452833                  040
1065673  ICS209_2009_KS-DDQ-128                 None
1634979  ICS209_2009_KS-DDQ-128                 None
1825692  SFO-2015CACDFLNU003791                 None
1870332  SFO-2015CACDFLNU003791                 None
==================================================
                         FPA_ID LOCAL_INCIDENT_ID
21986                FS-1452833                19
1565829              FS-1452833                 8
1065673  ICS209_2009_KS-DDQ-128              None
1634979  ICS209_2009_KS-DDQ-128              None
1825692  SFO-2015CACDFLNU003791         LNU003791
1870332  SFO-2015CACDFLNU003791         LNU003791
==================================================
                         FPA_ID FIRE_CODE
21986                FS-1452833      C64T
1565829              FS-1452833      G0QG
1065673  ICS209_2009_KS-DDQ-128      None
1634979  ICS209_2009_KS-DDQ-128      None
1825692  SFO-2015CACDFLNU003791      None
1870332  SFO-2015CACDFLNU003791      None
==================================================
                         FPA_ID         FIRE_NAME
21986                FS-1452833         SAN MATEO
1565829              FS-1452833         SAN MATEO
1065673  ICS209_2009_KS-DDQ-128           MA-KILO
1634979  ICS209_2009_KS-DDQ-128  TRAINING AREA 60
1825692  SFO-2015CACDFLNU003791              None
1870332  SFO-2015CACDFLNU003791              None
==================================================
                         FPA_ID      ICS_209_NAME
21986                FS-1452833              None
1565829              FS-1452833              None
1065673  ICS209_2009_KS-DDQ-128           MA-Kilo
1634979  ICS209_2009_KS-DDQ-128  Training Area 60
1825692  SFO-2015CACDFLNU003791              None
1870332  SFO-2015CACDFLNU003791              None
==================================================
                         FPA_ID  FIRE_YEAR
21986                FS-1452833       2007
1565829              FS-1452833       2012
1065673  ICS209_2009_KS-DDQ-128       2009
1634979  ICS209_2009_KS-DDQ-128       2012
1825692  SFO-2015CACDFLNU003791       2015
1870332  SFO-2015CACDFLNU003791       2015
==================================================
                         FPA_ID  DISCOVERY_DATE
21986                FS-1452833       2454299.5
1565829              FS-1452833       2456111.5
1065673  ICS209_2009_KS-DDQ-128       2454881.5
1634979  ICS209_2009_KS-DDQ-128       2455990.5
1825692  SFO-2015CACDFLNU003791       2457154.5
1870332  SFO-2015CACDFLNU003791       2457204.5
==================================================
                         FPA_ID  DISCOVERY_DAY
21986                FS-1452833            199
1565829              FS-1452833            185
1065673  ICS209_2009_KS-DDQ-128             50
1634979  ICS209_2009_KS-DDQ-128             64
1825692  SFO-2015CACDFLNU003791            132
1870332  SFO-2015CACDFLNU003791            182
==================================================
                         FPA_ID DISCOVERY_TIME
21986                FS-1452833           1030
1565829              FS-1452833           1500
1065673  ICS209_2009_KS-DDQ-128           1400
1634979  ICS209_2009_KS-DDQ-128           1300
1825692  SFO-2015CACDFLNU003791           1031
1870332  SFO-2015CACDFLNU003791           1751
==================================================
                         FPA_ID  STAT_CAUSE_CODE
21986                FS-1452833              1.0
1565829              FS-1452833              1.0
1065673  ICS209_2009_KS-DDQ-128             13.0
1634979  ICS209_2009_KS-DDQ-128             13.0
1825692  SFO-2015CACDFLNU003791              5.0
1870332  SFO-2015CACDFLNU003791             13.0
==================================================
                         FPA_ID   STAT_CAUSE_DESCR
21986                FS-1452833          Lightning
1565829              FS-1452833          Lightning
1065673  ICS209_2009_KS-DDQ-128  Missing/Undefined
1634979  ICS209_2009_KS-DDQ-128  Missing/Undefined
1825692  SFO-2015CACDFLNU003791     Debris Burning
1870332  SFO-2015CACDFLNU003791  Missing/Undefined
==================================================
                         FPA_ID  CONT_DATE
21986                FS-1452833  2454307.5
1565829              FS-1452833  2456112.5
1065673  ICS209_2009_KS-DDQ-128  2454881.5
1634979  ICS209_2009_KS-DDQ-128  2456020.5
1825692  SFO-2015CACDFLNU003791  2457154.5
1870332  SFO-2015CACDFLNU003791        NaN
==================================================
                         FPA_ID  CONT_DAY
21986                FS-1452833     207.0
1565829              FS-1452833     186.0
1065673  ICS209_2009_KS-DDQ-128      50.0
1634979  ICS209_2009_KS-DDQ-128      94.0
1825692  SFO-2015CACDFLNU003791     132.0
1870332  SFO-2015CACDFLNU003791       NaN
==================================================
                         FPA_ID CONT_TIME
21986                FS-1452833      1500
1565829              FS-1452833      1400
1065673  ICS209_2009_KS-DDQ-128      1930
1634979  ICS209_2009_KS-DDQ-128      1500
1825692  SFO-2015CACDFLNU003791      1050
1870332  SFO-2015CACDFLNU003791      None
==================================================
                         FPA_ID  FIRE_SIZE
21986                FS-1452833       4.25
1565829              FS-1452833       0.10
1065673  ICS209_2009_KS-DDQ-128    2490.00
1634979  ICS209_2009_KS-DDQ-128    2200.00
1825692  SFO-2015CACDFLNU003791       0.52
1870332  SFO-2015CACDFLNU003791       0.01
==================================================
                         FPA_ID FIRE_SIZE_CLASS
21986                FS-1452833               B
1565829              FS-1452833               A
1065673  ICS209_2009_KS-DDQ-128               F
1634979  ICS209_2009_KS-DDQ-128               F
1825692  SFO-2015CACDFLNU003791               B
1870332  SFO-2015CACDFLNU003791               A
==================================================
                         FPA_ID   LATITUDE
21986                FS-1452833  35.312778
1565829              FS-1452833  35.337222
1065673  ICS209_2009_KS-DDQ-128  39.234444
1634979  ICS209_2009_KS-DDQ-128  39.220000
1825692  SFO-2015CACDFLNU003791  38.715883
1870332  SFO-2015CACDFLNU003791  38.342004
==================================================
                         FPA_ID   LONGITUDE
21986                FS-1452833 -107.593056
1565829              FS-1452833 -107.779444
1065673  ICS209_2009_KS-DDQ-128  -96.830278
1634979  ICS209_2009_KS-DDQ-128  -96.940000
1825692  SFO-2015CACDFLNU003791 -122.994933
1870332  SFO-2015CACDFLNU003791 -121.958596
==================================================
                         FPA_ID  OWNER_CODE
21986                FS-1452833         5.0
1565829              FS-1452833         5.0
1065673  ICS209_2009_KS-DDQ-128         6.0
1634979  ICS209_2009_KS-DDQ-128         6.0
1825692  SFO-2015CACDFLNU003791        15.0
1870332  SFO-2015CACDFLNU003791        14.0
==================================================
                         FPA_ID            OWNER_DESCR
21986                FS-1452833                   USFS
1565829              FS-1452833                   USFS
1065673  ICS209_2009_KS-DDQ-128          OTHER FEDERAL
1634979  ICS209_2009_KS-DDQ-128          OTHER FEDERAL
1825692  SFO-2015CACDFLNU003791      UNDEFINED FEDERAL
1870332  SFO-2015CACDFLNU003791  MISSING/NOT SPECIFIED
==================================================
                         FPA_ID  COUNTY
21986                FS-1452833      31
1565829              FS-1452833     031
1065673  ICS209_2009_KS-DDQ-128   Riley
1634979  ICS209_2009_KS-DDQ-128   Riley
1825692  SFO-2015CACDFLNU003791  SONOMA
1870332  SFO-2015CACDFLNU003791  SOLANO
==================================================
                         FPA_ID FIPS_CODE
21986                FS-1452833       031
1565829              FS-1452833       031
1065673  ICS209_2009_KS-DDQ-128       161
1634979  ICS209_2009_KS-DDQ-128       161
1825692  SFO-2015CACDFLNU003791       097
1870332  SFO-2015CACDFLNU003791       095
==================================================
                         FPA_ID FIPS_NAME
21986                FS-1452833  McKinley
1565829              FS-1452833  McKinley
1065673  ICS209_2009_KS-DDQ-128     Riley
1634979  ICS209_2009_KS-DDQ-128     Riley
1825692  SFO-2015CACDFLNU003791    Sonoma
1870332  SFO-2015CACDFLNU003791    Solano
==================================================
                         FPA_ID       DATE
21986                FS-1452833 2007-07-18
1565829              FS-1452833 2012-07-03
1065673  ICS209_2009_KS-DDQ-128 2009-02-19
1634979  ICS209_2009_KS-DDQ-128 2012-03-04
1825692  SFO-2015CACDFLNU003791 2015-05-12
1870332  SFO-2015CACDFLNU003791 2015-07-01
==================================================
                         FPA_ID CONT_DATE_COR
21986                FS-1452833    2007-07-26
1565829              FS-1452833    2012-07-04
1065673  ICS209_2009_KS-DDQ-128    2009-02-19
1634979  ICS209_2009_KS-DDQ-128    2012-04-03
1825692  SFO-2015CACDFLNU003791    2015-05-12
1870332  SFO-2015CACDFLNU003791           NaT
==================================================
                         FPA_ID  CONT_DATE_COR_INT
21986                FS-1452833               2007
1565829              FS-1452833               2012
1065673  ICS209_2009_KS-DDQ-128               2009
1634979  ICS209_2009_KS-DDQ-128               2012
1825692  SFO-2015CACDFLNU003791               2015
1870332  SFO-2015CACDFLNU003791                  0
==================================================
                         FPA_ID  DIFF_YEAR
21986                FS-1452833          0
1565829              FS-1452833          0
1065673  ICS209_2009_KS-DDQ-128          0
1634979  ICS209_2009_KS-DDQ-128          0
1825692  SFO-2015CACDFLNU003791          0
1870332  SFO-2015CACDFLNU003791      -2015
==================================================
                         FPA_ID FIRE_SIZE_CLASS_TEST
21986                FS-1452833                    B
1565829              FS-1452833                    A
1065673  ICS209_2009_KS-DDQ-128                    F
1634979  ICS209_2009_KS-DDQ-128                    F
1825692  SFO-2015CACDFLNU003791                    B
1870332  SFO-2015CACDFLNU003791                    A
==================================================

C:\Users\Enedis\AppData\Local\Temp\ipykernel_14112\1141412449.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fpa_doublon.sort_values(by = 'FPA_ID', inplace = True)

# Examen des causes des incendies

In [263]:
#plt.figure(figsize=(10, 8))
#plt.barh(fires['STAT_CAUSE_DESCR'].value_counts(), color = 'darkslateblue', width = 0.6)
#plt.title(label = 'XXXX', size = 'xx-large', weight = 'bold', color = 'crimson')
#plt.xlabel('XXXX', weight = 'bold')
#plt.show()

Il y a 13 causes répertoriées dans l'ensemble de données. 
Les incendies sont-ils plus probables certains jours de la semaine ?

In [264]:
#fires['DAY_OF_WEEK'].value_counts().plot(kind='barh',color='navy')
#plt.show()

Les incendies sont légèrement plus susceptibles de se déclencher le week-end. 
On peut supposer que les incendies sont déclenchés par des personnes négligentes : feux de camp, cigarettes, incendies malveillants.
Il est peu probable que les incendies augmentant le week-end proviennent de causes naturelles, comme la foudre par exemple. Nous pouvons tester cela :

In [265]:
#fires_lightning = fires[fires['STAT_CAUSE_DESCR']=='Lightning']
#fires_lightning['DAY_OF_WEEK'].value_counts().plot(kind='barh',color='navy')
#plt.show()

Il y a quelques petites variations, mais nous voyons que les feux se déclenchant le week-end sont moins élevés. 
Nous pouvons examiner si l'augmentation générale du week-end est due à des incendies malveillants
Incendie criminel :

In [266]:
#fires_arson = fires[fires['STAT_CAUSE_DESCR']=='Arson']
#fires_arson['DAY_OF_WEEK'].value_counts().plot(kind='barh',color='navy')
#plt.show()

Cela montre une tendance plus significative.
Les incendies criminels sont plus probables le week-end que pendant la semaine, cela représente une augmentation d'environ 30 % de la moyenne des jours de la semaine. 

Quels États ont le plus d'incendies ? (pour éviter un trop grand nombre de données, nous pouvons nous concentrer sur les dix premiers)

In [267]:
#fires['STATE'].value_counts().head(n=10).plot(kind='barh',color='navy')
#plt.show()

CA et TX sont dans le top 3, ce sont de grands états avec des climats secs. En revanche, GA est également dans le top 3 on peut se demander pourquoi
Nous pouvons enquêter sur les causes des incendies dans ces 3 états et rechercher des différences. On extrait les données pour ces 3 états :

In [268]:
#df_CA = df[df['STATE']=='CA']
#df_GA = df[df['STATE']=='GA']
#df_TX = df[df['STATE']=='TX']

In [269]:
#fires_CA['STAT_CAUSE_DESCR'].value_counts().plot(kind='barh',color='navy',title='causes of fires for CA')
#plt.show()

In [270]:
#fires_GA['STAT_CAUSE_DESCR'].value_counts().plot(kind='barh',color='navy',title='causes of fires for GA')
#plt.show()

In [271]:
#fires_TX['STAT_CAUSE_DESCR'].value_counts().plot(kind='barh',color='navy',title='causes of fires for TX')
#plt.show()

Il existe des différences entre les états. 
Il existe deux manières de déterminer l'emplacement d'un incendie dans ce jeu de données - ETAT ou LATITUDE + LONGITUDE
Nous pouvons avoir une idée de la couverture géographique des données en traçant chaque paire de latitude et de longitude

In [272]:
#fires.plot(kind='scatter',x='LONGITUDE',y='LATITUDE',color='coral',alpha=0.3)
#plt.show()